name: Build Flet App
on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout project
        uses: actions/checkout@v4

      - name: Setup Java JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install "flet[all]"

      - name: Accept Android Licenses
        run: |
          yes | flutter doctor --android-licenses

      - name: Build Android APK
        run: |
          # Команда 'yes' автоматически отвечает 'y' на все внутренние вопросы Flet CLI
          yes | flet build apk --project "my_flet_app" --product "My App" --org "com.example"

      - name: Upload APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: my-flet-app-apk
          path: build/apk/*.apk
